//! THIR → Python 3.12+ source code emitter.
//!
//! Walks the [`ThirModule`] tree and writes readable Python with type annotations.

use std::fmt::Write;

use asatsuyu_ast::{BinOp, UnOp};
use asatsuyu_hir::{DefKind, HirCustomType, HirFieldType, HirTypeExpr, HirVariant};
use asatsuyu_syntax::Span;
use asatsuyu_ty::{PrimTy, ThirExpr, ThirFnDef, ThirMatchArm, ThirModule, ThirPattern, Ty};
use smol_str::SmolStr;

/// 4-space indentation per PEP 8.
const INDENT: &str = "    ";

/// Precomputed line-start byte offsets for source-map comment generation.
pub(crate) struct LineOffsets {
    offsets: Vec<u32>,
}

impl LineOffsets {
    /// Build a line offset table from source text.
    pub(crate) fn from_source(source: &str) -> Self {
        let mut offsets = vec![0u32];
        for (i, ch) in source.char_indices() {
            if ch == '\n' {
                // Source files are capped well below u32::MAX.
                #[allow(clippy::cast_possible_truncation)]
                offsets.push((i + 1) as u32);
            }
        }
        Self { offsets }
    }

    /// Convert a byte offset to a 1-based line number.
    fn line_number(&self, offset: u32) -> usize {
        match self.offsets.binary_search(&offset) {
            Ok(i) => i + 1,
            Err(i) => i,
        }
    }
}

/// Emits Python source code from a typed HIR module.
pub(crate) struct Emitter<'a> {
    module: &'a ThirModule,
    output: String,
    indent: usize,
    /// Source-map line offsets. `Some` enables `# asty:L<n>` comments.
    line_offsets: Option<LineOffsets>,
}

impl<'a> Emitter<'a> {
    pub(crate) fn new(module: &'a ThirModule) -> Self {
        Self { module, output: String::new(), indent: 0, line_offsets: None }
    }

    /// Create an emitter with source-map comment generation enabled.
    pub(crate) fn with_source_map(module: &'a ThirModule, source: &str) -> Self {
        Self {
            module,
            output: String::new(),
            indent: 0,
            line_offsets: Some(LineOffsets::from_source(source)),
        }
    }

    pub(crate) fn emit(&mut self) {
        self.emit_module();
    }

    pub(crate) fn into_output(self) -> String {
        self.output
    }

    // ── Source-map helpers ─────────────────────────────────────────

    /// Append a `# asty:L<n>` comment before the trailing newline on the
    /// current output line. No-op when source-map is disabled.
    fn write_source_comment(&mut self, span: Span) {
        if let Some(ref lo) = self.line_offsets {
            let line = lo.line_number(span.start);
            let _ = write!(self.output, "  # asty:L{line}");
        }
    }

    // ── Indent helpers ─────────────────────────────────────────────

    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str(INDENT);
        }
    }

    fn push_indent(&mut self) {
        self.indent += 1;
    }

    fn pop_indent(&mut self) {
        self.indent -= 1;
    }

    // ── Module ─────────────────────────────────────────────────────

    fn emit_module(&mut self) {
        let has_custom_types = !self.module.custom_types.is_empty();
        let has_functions = !self.module.functions.is_empty();
        let has_imports = !self.module.imports.is_empty();

        if !has_custom_types && !has_functions && !has_imports {
            return;
        }

        // 1. Header comment.
        self.output.push_str("# Generated by Asatsuyu \u{2014} do not edit\n");

        // 2. Imports.
        for import in &self.module.imports {
            let bound_name = &self.module.symbol_table.get(import.def_id).name;
            let module_name = import
                .module_path
                .iter()
                .map(smol_str::SmolStr::as_str)
                .collect::<Vec<_>>()
                .join(".");
            let needs_alias = import.module_path.last().is_none_or(|last| last != bound_name);
            if needs_alias {
                let _ = writeln!(self.output, "import {module_name} as {bound_name}");
            } else {
                let _ = writeln!(self.output, "import {module_name}");
            }
        }
        if has_custom_types {
            self.output.push_str("from dataclasses import dataclass\n");
        }

        // 3. ADT definitions.
        for ct in &self.module.custom_types {
            self.output.push_str("\n\n");
            self.emit_custom_type(ct);
        }

        // 4. Function definitions.
        for fn_def in &self.module.functions {
            self.output.push_str("\n\n");
            self.emit_fn_def(fn_def);
        }
    }

    // ── Custom type (ADT → dataclass) ─────────────────────────────

    fn emit_custom_type(&mut self, ct: &HirCustomType) {
        let type_name = self.module.symbol_table.get(ct.def_id).name.clone();
        let param_map = build_type_param_map(&ct.type_params);

        // Emit each variant as a @dataclass.
        for (i, variant) in ct.variants.iter().enumerate() {
            if i > 0 {
                self.output.push_str("\n\n");
            }
            self.emit_variant(variant, &param_map);
        }

        // Emit PEP 695 type alias for multi-variant ADTs.
        if ct.variants.len() > 1 {
            self.output.push_str("\n\n");
            self.emit_type_alias(ct, &type_name, &param_map);
        }
    }

    fn emit_variant(&mut self, variant: &HirVariant, param_map: &[(SmolStr, String)]) {
        let name = &self.module.symbol_table.get(variant.def_id).name;
        let py_name = sanitize_python_name(name);

        self.output.push_str("@dataclass(frozen=True, slots=True)\n");
        let _ = write!(self.output, "class {py_name}");

        // PEP 695 type parameters.
        let used_params = collect_used_params(&variant.fields, param_map);
        if !used_params.is_empty() {
            let _ = write!(self.output, "[{}]", used_params.join(", "));
        }

        self.output.push_str(":\n");

        if variant.fields.is_empty() {
            self.output.push_str("    pass\n");
        } else {
            for (i, field) in variant.fields.iter().enumerate() {
                let field_name = field
                    .label
                    .as_ref()
                    .map_or_else(|| format!("_{i}"), |l| sanitize_python_name(l));
                let py_type = hir_type_expr_to_python(&field.type_expr, param_map);
                let _ = writeln!(self.output, "    {field_name}: {py_type}");
            }
        }
    }

    fn emit_type_alias(
        &mut self,
        ct: &HirCustomType,
        type_name: &str,
        param_map: &[(SmolStr, String)],
    ) {
        let _ = write!(self.output, "type {type_name}");
        if !param_map.is_empty() {
            let params: Vec<&str> = param_map.iter().map(|(_, p)| p.as_str()).collect();
            let _ = write!(self.output, "[{}]", params.join(", "));
        }
        self.output.push_str(" = ");

        for (i, variant) in ct.variants.iter().enumerate() {
            if i > 0 {
                self.output.push_str(" | ");
            }
            let name = &self.module.symbol_table.get(variant.def_id).name;
            let py_name = sanitize_python_name(name);
            self.output.push_str(&py_name);

            let used = collect_used_params(&variant.fields, param_map);
            if !used.is_empty() {
                let _ = write!(self.output, "[{}]", used.join(", "));
            }
        }
        self.output.push('\n');
    }

    // ── Function ───────────────────────────────────────────────────

    fn emit_fn_def(&mut self, fn_def: &ThirFnDef) {
        // def name(params) -> return_ty:
        self.write_indent();
        let name = &self.module.symbol_table.get(fn_def.def_id).name;
        let _ = write!(self.output, "def {name}(");

        for (i, param) in fn_def.params.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            let param_name = &self.module.symbol_table.get(param.def_id).name;
            let _ = write!(self.output, "{param_name}: {}", ty_to_python(&param.ty));
        }

        let _ = write!(self.output, ") -> {}:", ty_to_python(&fn_def.return_ty));
        self.write_source_comment(fn_def.span);
        self.output.push('\n');

        // Body.
        self.push_indent();
        self.emit_body(&fn_def.body);
        self.pop_indent();
    }

    // ── Body (block handling) ──────────────────────────────────────

    fn emit_body(&mut self, body: &ThirExpr) {
        match body {
            ThirExpr::Block { exprs, .. } if exprs.is_empty() => {
                self.write_indent();
                self.output.push_str("pass\n");
            }
            ThirExpr::Block { exprs, .. } => {
                let (statements, last) = exprs.split_at(exprs.len() - 1);
                for stmt in statements {
                    self.emit_stmt(stmt);
                }
                self.emit_return_stmt(&last[0]);
            }
            // Non-block body (single expression).
            other => {
                self.emit_return_stmt(other);
            }
        }
    }

    // ── Statements ─────────────────────────────────────────────────

    fn emit_stmt(&mut self, expr: &ThirExpr) {
        if let ThirExpr::Match { subject, arms, .. } = expr {
            self.emit_match_stmt(subject, arms, false);
            return;
        }
        self.write_indent();
        self.emit_expr(expr);
        self.output.push('\n');
    }

    fn emit_return_stmt(&mut self, expr: &ThirExpr) {
        if let ThirExpr::Match { subject, arms, .. } = expr {
            self.emit_match_stmt(subject, arms, true);
            return;
        }
        self.write_indent();
        self.output.push_str("return ");
        self.emit_expr(expr);
        self.write_source_comment(expr.span());
        self.output.push('\n');
    }

    // ── Expressions (inline, no newline) ───────────────────────────

    fn emit_expr(&mut self, expr: &ThirExpr) {
        match expr {
            ThirExpr::Literal(lit) => {
                self.output.push_str(lit.value.as_str());
            }
            ThirExpr::Var { def_id, .. } => {
                let def = self.module.symbol_table.get(*def_id);
                if def.kind == DefKind::Constructor {
                    self.output.push_str(&sanitize_python_name(&def.name));
                } else {
                    self.output.push_str(def.name.as_str());
                }
            }
            ThirExpr::Block { exprs, .. } => {
                // Nested block in expression position: emit the last expression.
                if let Some(last) = exprs.last() {
                    self.emit_expr(last);
                }
            }
            ThirExpr::Call { func, args, .. } => {
                if self.emit_builtin_call(func, args) {
                    return;
                }
                self.emit_expr(func);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.emit_expr(arg);
                }
                self.output.push(')');
            }
            ThirExpr::BinaryOp { op, lhs, rhs, .. } => {
                self.output.push('(');
                self.emit_expr(lhs);
                self.output.push_str(binop_to_python(*op));
                self.emit_expr(rhs);
                self.output.push(')');
            }
            ThirExpr::UnaryOp { op, expr, .. } => {
                self.output.push('(');
                self.output.push_str(unop_to_python(*op));
                self.emit_expr(expr);
                self.output.push(')');
            }
            ThirExpr::If { condition, then_body, else_body, .. } => {
                // Python ternary: (then if cond else else_)
                self.output.push('(');
                self.emit_expr(then_body);
                self.output.push_str(" if ");
                self.emit_expr(condition);
                self.output.push_str(" else ");
                if let Some(else_expr) = else_body {
                    self.emit_expr(else_expr);
                } else {
                    self.output.push_str("None");
                }
                self.output.push(')');
            }
            ThirExpr::Match { arms, .. } => {
                // Fallback for match in inline expression position.
                // Proper match/case is emitted in emit_return_stmt/emit_stmt.
                if let Some(first) = arms.first() {
                    self.emit_expr(&first.body);
                }
            }
            ThirExpr::Let { binding, value, .. } => {
                let name = &self.module.symbol_table.get(*binding).name;
                self.output.push_str(name.as_str());
                self.output.push_str(" = ");
                self.emit_expr(value);
            }
            ThirExpr::Lambda { params, body, .. } => {
                self.output.push_str("lambda ");
                for (i, p) in params.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    let name = &self.module.symbol_table.get(p.def_id).name;
                    self.output.push_str(name.as_str());
                }
                self.output.push_str(": ");
                self.emit_expr(body);
            }
        }
    }

    fn emit_builtin_call(&mut self, func: &ThirExpr, args: &[ThirExpr]) -> bool {
        let ThirExpr::Var { def_id, .. } = func else {
            return false;
        };
        let name = self.module.symbol_table.get(*def_id).name.as_str();
        if name == "string_concat" && args.len() == 2 {
            self.output.push('(');
            self.emit_expr(&args[0]);
            self.output.push_str(" + ");
            self.emit_expr(&args[1]);
            self.output.push(')');
            true
        } else {
            false
        }
    }

    // ── Match statement emission ──────────────────────────────────

    fn emit_match_stmt(&mut self, subject: &ThirExpr, arms: &[ThirMatchArm], is_return: bool) {
        self.write_indent();
        self.output.push_str("match ");
        self.emit_expr(subject);
        self.output.push(':');
        self.write_source_comment(subject.span());
        self.output.push('\n');
        self.push_indent();
        for arm in arms {
            self.write_indent();
            self.output.push_str("case ");
            self.emit_pattern(&arm.pattern);
            self.output.push(':');
            self.write_source_comment(arm.span);
            self.output.push('\n');
            self.push_indent();
            if is_return {
                self.emit_return_stmt(&arm.body);
            } else {
                self.emit_stmt(&arm.body);
            }
            self.pop_indent();
        }
        self.pop_indent();
    }

    fn emit_pattern(&mut self, pattern: &ThirPattern) {
        match pattern {
            ThirPattern::Wildcard(_) => {
                self.output.push('_');
            }
            ThirPattern::Variable { def_id, .. } => {
                let name = &self.module.symbol_table.get(*def_id).name;
                self.output.push_str(name.as_str());
            }
            ThirPattern::Literal(lit) => {
                self.output.push_str(lit.value.as_str());
            }
            ThirPattern::Constructor { def_id, fields, .. } => {
                let name = &self.module.symbol_table.get(*def_id).name;
                let py_name = sanitize_python_name(name);
                self.output.push_str(&py_name);
                if fields.is_empty() {
                    // Nullary constructors need `()` in patterns to match as class.
                    self.output.push_str("()");
                } else {
                    self.output.push('(');
                    for (i, field) in fields.iter().enumerate() {
                        if i > 0 {
                            self.output.push_str(", ");
                        }
                        self.emit_pattern(field);
                    }
                    self.output.push(')');
                }
            }
            ThirPattern::Tuple { elements, .. } => {
                self.output.push('(');
                for (i, elem) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.emit_pattern(elem);
                }
                // Single-element tuples need a trailing comma.
                if elements.len() == 1 {
                    self.output.push(',');
                }
                self.output.push(')');
            }
            ThirPattern::List { elements, rest, .. } => {
                self.output.push('[');
                for (i, elem) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.emit_pattern(elem);
                }
                if let Some(rest_pat) = rest {
                    if !elements.is_empty() {
                        self.output.push_str(", ");
                    }
                    self.output.push('*');
                    self.emit_pattern(rest_pat);
                }
                self.output.push(']');
            }
        }
    }
}

// ── Type mapping ───────────────────────────────────────────────────

/// Map a binary operator to its Python syntax (with surrounding spaces).
fn binop_to_python(op: BinOp) -> &'static str {
    match op {
        BinOp::Add | BinOp::StringConcat => " + ",
        BinOp::Sub => " - ",
        BinOp::Mul => " * ",
        BinOp::Div => " / ",
        BinOp::Mod => " % ",
        BinOp::Eq => " == ",
        BinOp::NotEq => " != ",
        BinOp::Lt => " < ",
        BinOp::LtEq => " <= ",
        BinOp::Gt => " > ",
        BinOp::GtEq => " >= ",
        BinOp::And => " and ",
        BinOp::Or => " or ",
    }
}

/// Map a unary operator to its Python syntax.
fn unop_to_python(op: UnOp) -> &'static str {
    match op {
        UnOp::Neg => "-",
        UnOp::Not => "not ",
    }
}

/// Map an Asatsuyu [`Ty`] to its Python type annotation string.
fn ty_to_python(ty: &Ty) -> String {
    match ty {
        Ty::Primitive(PrimTy::Int) => "int".into(),
        Ty::Primitive(PrimTy::Float) => "float".into(),
        Ty::Primitive(PrimTy::String) => "str".into(),
        Ty::Primitive(PrimTy::Bool) => "bool".into(),
        Ty::Primitive(PrimTy::None) => "None".into(),
        Ty::Named { name, args, .. } => {
            if args.is_empty() {
                name.to_string()
            } else {
                let arg_strs: Vec<String> = args.iter().map(ty_to_python).collect();
                format!("{name}[{}]", arg_strs.join(", "))
            }
        }
        Ty::Function { .. } | Ty::Var(_) | Ty::Error => "Any".into(),
    }
}

// ── ADT helpers ───────────────────────────────────────────────────

/// Python keywords and builtins that must be suffixed with `_` when used as names.
const PYTHON_RESERVED: &[&str] = &[
    "None", "True", "False", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield",
];

/// Append `_` to names that collide with Python keywords.
fn sanitize_python_name(name: &str) -> String {
    if PYTHON_RESERVED.contains(&name) { format!("{name}_") } else { name.to_string() }
}

/// Map Asatsuyu type parameter names to PEP 695 convention.
///
/// `["a"]` → `[("a", "T")]`, `["a", "b"]` → `[("a", "T"), ("b", "E")]`.
fn build_type_param_map(params: &[SmolStr]) -> Vec<(SmolStr, String)> {
    const NAMES: &[&str] = &["T", "U", "V", "W"];
    params
        .iter()
        .enumerate()
        .map(|(i, name)| {
            let py = if i < NAMES.len() { NAMES[i].to_string() } else { format!("T{i}") };
            (name.clone(), py)
        })
        .collect()
}

/// Convert an [`HirTypeExpr`] to a Python type annotation string.
///
/// Applies the type parameter mapping (e.g., `a` → `T`) and converts
/// primitive type names to Python equivalents.
fn hir_type_expr_to_python(te: &HirTypeExpr, param_map: &[(SmolStr, String)]) -> String {
    // Check if it's a mapped type parameter.
    if let Some((_, py_name)) = param_map.iter().find(|(asty, _)| *asty == te.name) {
        return py_name.clone();
    }

    // Primitive type names.
    let base = match te.name.as_str() {
        "Int" => "int",
        "Float" => "float",
        "String" => "str",
        "Bool" => "bool",
        "None" => "None",
        _ => te.name.as_str(),
    };

    if te.args.is_empty() {
        base.to_string()
    } else {
        let args: Vec<String> =
            te.args.iter().map(|a| hir_type_expr_to_python(a, param_map)).collect();
        format!("{base}[{}]", args.join(", "))
    }
}

/// Collect type parameter names actually used in a variant's fields.
fn collect_used_params(fields: &[HirFieldType], param_map: &[(SmolStr, String)]) -> Vec<String> {
    let mut used = Vec::new();
    for (asty_name, py_name) in param_map {
        if fields.iter().any(|f| type_expr_mentions(asty_name, &f.type_expr)) {
            used.push(py_name.clone());
        }
    }
    used
}

/// Check if a type expression mentions a given name (type parameter).
fn type_expr_mentions(name: &SmolStr, te: &HirTypeExpr) -> bool {
    if te.name == *name {
        return true;
    }
    te.args.iter().any(|a| type_expr_mentions(name, a))
}
