//! Python 3.12+ code generation for the Asatsuyu language.
//!
//! Transforms THIR into readable Python source code with type annotations.
//!
//! # Usage
//!
//! ```
//! use asatsuyu_ast::lower;
//! use asatsuyu_hir::lower_to_hir;
//! use asatsuyu_parser::parse;
//! use asatsuyu_syntax::FileId;
//! use asatsuyu_ty::check_types;
//! use asatsuyu_backend_python::emit_module;
//!
//! let cst = parse(FileId(0), "pub fn main() { 42 }");
//! let ast = lower(&cst, FileId(0));
//! let hir = lower_to_hir(&ast.module);
//! let thir = check_types(&hir.module);
//! let python = emit_module(&thir.module);
//! assert!(python.contains("def main()"));
//! assert!(python.contains("return 42"));
//! ```

mod emitter;

use asatsuyu_ty::ThirModule;

/// Emit Python 3.12+ source code from a type-checked module.
///
/// Produces readable Python with type annotations. Functions are separated
/// by two blank lines per PEP 8.
#[must_use]
pub fn emit_module(module: &ThirModule) -> String {
    let mut em = emitter::Emitter::new(module);
    em.emit();
    em.into_output()
}

#[cfg(test)]
mod tests {
    use super::*;
    use asatsuyu_parser::parse;
    use asatsuyu_syntax::FileId;

    const FID: FileId = FileId(0);

    /// Helper: source → CST → AST → HIR → THIR → Python.
    fn python_from_source(source: &str) -> String {
        let cst = parse(FID, source);
        let ast = asatsuyu_ast::lower(&cst, FID);
        let hir = asatsuyu_hir::lower_to_hir(&ast.module);
        let thir = asatsuyu_ty::check_types(&hir.module);
        emit_module(&thir.module)
    }

    // ── 1. Empty module ─────────────────────────────────────────────

    #[test]
    fn emit_empty_module() {
        let py = python_from_source("");
        assert_eq!(py, "");
    }

    // ── 2. hello.asty ───────────────────────────────────────────────

    #[test]
    fn emit_hello_asty() {
        let source = include_str!("../../../examples/hello.asty");
        let py = python_from_source(source);
        assert!(py.contains("def main() -> int:"), "output: {py}");
        assert!(py.contains("return 42"), "output: {py}");
        assert!(py.starts_with("# Generated by Asatsuyu"), "header: {py}");
    }

    // ── 3. greet.asty ───────────────────────────────────────────────

    #[test]
    fn emit_greet_asty() {
        let source = include_str!("../../../examples/greet.asty");
        let py = python_from_source(source);
        assert!(py.starts_with("# Generated by Asatsuyu"), "header: {py}");
        assert!(py.contains("def greet(name: str) -> str:"), "greet fn: {py}");
        assert!(py.contains("def add(x: int, y: int) -> int:"), "add fn: {py}");
    }

    // ── 4. String literal ───────────────────────────────────────────

    #[test]
    fn emit_string_literal() {
        let py = python_from_source(r#"fn f() { "hello" }"#);
        assert!(py.contains("return \"hello\""), "output: {py}");
    }

    // ── 5. Param types ──────────────────────────────────────────────

    #[test]
    fn emit_param_types() {
        let py = python_from_source("fn add(x: Int, y: Int) -> Int { x }");
        assert!(py.contains("x: int, y: int"), "output: {py}");
        assert!(py.contains("-> int:"), "output: {py}");
    }

    // ── 6. None return + empty body ─────────────────────────────────

    #[test]
    fn emit_none_return() {
        let py = python_from_source("fn f() { }");
        assert!(py.contains("-> None:"), "output: {py}");
        assert!(py.contains("pass"), "output: {py}");
    }

    // ── 7. Multi-expression block ───────────────────────────────────

    #[test]
    fn emit_multi_expr_block() {
        let py = python_from_source(r#"fn f() { 1 "hi" }"#);
        // First expr as statement, last as return.
        assert!(py.contains("    1\n"), "first expr as stmt: {py}");
        assert!(py.contains("    return \"hi\"\n"), "last expr as return: {py}");
    }

    // ── 8. Variable reference ───────────────────────────────────────

    #[test]
    fn emit_variable_ref() {
        let py = python_from_source("fn id(x: Int) -> Int { x }");
        assert!(py.contains("return x"), "output: {py}");
    }

    // ── 9. Two blank lines between functions ────────────────────────

    #[test]
    fn emit_two_blank_lines() {
        let py = python_from_source("fn a() { 1 }\nfn b() { 2 }");
        assert!(py.contains(":\n    return 1\n\n\ndef b("), "two blank lines: {py}");
    }

    // ── 10. Indentation ─────────────────────────────────────────────

    #[test]
    fn emit_indentation() {
        let py = python_from_source("fn f() { 42 }");
        // Body should be indented with 4 spaces.
        assert!(py.contains("    return 42"), "4-space indent: {py}");
        // def should not be indented (after the header).
        assert!(py.contains("\ndef f("), "no indent on def: {py}");
    }

    // ── 11. Output looks like valid Python ──────────────────────────

    #[test]
    fn emit_output_is_valid_python() {
        let py = python_from_source("pub fn main() { 42 }");
        // Basic structural checks.
        assert!(py.starts_with("# Generated by Asatsuyu"), "starts with header");
        assert!(py.contains("def main("), "has def");
        assert!(py.contains(":\n"), "has colon + newline");
        assert!(py.ends_with('\n'), "ends with newline");
    }

    // ── 12. No error types in valid output ──────────────────────────

    #[test]
    fn emit_readable() {
        let py = python_from_source(
            "pub fn greet(name: String) -> String { \"hello\" }\nfn add(x: Int, y: Int) -> Int { x }",
        );
        assert!(!py.contains("Any"), "no Any in valid output: {py}");
        assert!(!py.contains("<error>"), "no <error> in valid output: {py}");
    }

    #[test]
    fn emit_string_concat_as_python_plus() {
        let py = python_from_source(r#"fn f(name: String) -> String { "Hello, " <> name }"#);
        assert!(py.contains("return (\"Hello, \" + name)"), "output: {py}");
        assert!(!py.contains("string_concat("), "output: {py}");
    }

    // ── Issue 29: Module structure ─────────────────────────────────

    #[test]
    fn emit_module_header() {
        let py = python_from_source("fn f() { 42 }");
        assert!(
            py.starts_with("# Generated by Asatsuyu"),
            "non-empty module should have header: {py}",
        );
    }

    #[test]
    fn emit_dataclass_import() {
        let py = python_from_source("type Color { Red Green Blue }\nfn f() { 1 }");
        assert!(
            py.contains("from dataclasses import dataclass"),
            "ADT module should import dataclass: {py}",
        );
    }

    #[test]
    fn emit_no_dataclass_import_without_adt() {
        let py = python_from_source("fn f() { 1 }");
        assert!(
            !py.contains("from dataclasses import dataclass"),
            "no ADT → no dataclass import: {py}",
        );
    }

    #[test]
    fn emit_plain_imports() {
        let py = python_from_source("import gleam.io\nfn f() { io }");
        assert!(py.contains("import gleam.io\n"), "plain import: {py}");
    }

    #[test]
    fn emit_import_aliases() {
        let py = python_from_source("import gleam.io as stdio\nfn f() { stdio }");
        assert!(py.contains("import gleam.io as stdio\n"), "aliased import: {py}");
    }

    // ── Issue 30: ADT as dataclasses ───────────────────────────────

    #[test]
    fn emit_record_type() {
        // Go-style record type: labels are preserved.
        let py = python_from_source("type User { name: String  age: Int }");
        assert!(py.contains("@dataclass(frozen=True, slots=True)"), "decorator: {py}");
        assert!(py.contains("class User:"), "class name: {py}");
        assert!(py.contains("    name: str"), "field name: {py}");
        assert!(py.contains("    age: int"), "field age: {py}");
        // Single-variant record should not have a type alias.
        assert!(!py.contains("type User ="), "no type alias for record: {py}");
    }

    #[test]
    fn emit_single_variant_adt() {
        // Variant-style single constructor: positional fields.
        let py = python_from_source("type Wrapper { Wrapper(String, Int) }");
        assert!(py.contains("class Wrapper:"), "class: {py}");
        assert!(py.contains("    _0: str"), "field 0: {py}");
        assert!(py.contains("    _1: int"), "field 1: {py}");
    }

    #[test]
    fn emit_option_adt() {
        let py = python_from_source("type Option(a) { Some(a) None }");
        // Two dataclasses.
        assert!(py.contains("class Some[T]:"), "Some class: {py}");
        assert!(py.contains("class None_:"), "None class (sanitized): {py}");
        assert!(py.contains("    _0: T"), "Some field: {py}");
        assert!(py.contains("    pass"), "None pass: {py}");
        // Type alias.
        assert!(py.contains("type Option[T] = Some[T] | None_"), "type alias: {py}");
    }

    #[test]
    fn emit_result_adt() {
        let py = python_from_source("type Result(a, e) { Ok(a) Error(e) }");
        assert!(py.contains("class Ok[T]:"), "Ok class: {py}");
        assert!(py.contains("class Error[U]:"), "Error class: {py}");
        assert!(py.contains("type Result[T, U] = Ok[T] | Error[U]"), "type alias: {py}");
    }

    #[test]
    fn emit_nullary_constructor() {
        let py = python_from_source("type Color { Red Green Blue }");
        assert!(py.contains("class Red:\n    pass"), "Red: {py}");
        assert!(py.contains("class Green:\n    pass"), "Green: {py}");
        assert!(py.contains("class Blue:\n    pass"), "Blue: {py}");
        assert!(py.contains("type Color = Red | Green | Blue"), "type alias: {py}");
    }

    #[test]
    fn emit_adt_before_functions() {
        let source = "type Color { Red Blue }\nfn f() { 1 }";
        let py = python_from_source(source);
        let class_pos = py.find("class Red").expect("Red class");
        let fn_pos = py.find("def f(").expect("f function");
        assert!(class_pos < fn_pos, "ADT should appear before functions: {py}");
    }

    #[test]
    fn emit_constructor_call_in_expression() {
        let source = "
            type Option(a) { Some(a) None }
            pub fn wrap(x: Int) -> Option(Int) { Some(x) }
        ";
        let py = python_from_source(source);
        assert!(py.contains("return Some(x)"), "constructor call: {py}");
    }

    #[test]
    fn emit_adt_with_match() {
        let source = "
            type Option(a) { Some(a) None }
            pub fn unwrap_or(opt: Option(Int), default: Int) -> Int {
                match opt {
                    Some(x) -> x
                    None -> default
                }
            }
        ";
        let py = python_from_source(source);
        assert!(py.contains("case Some(x):"), "Some pattern: {py}");
        assert!(py.contains("case None_():"), "None pattern (sanitized): {py}");
    }
}
