//! Static prelude template for the Asatsuyu Python runtime.
//!
//! Contains `Ok`, `Error`, and `Result` type definitions that generated
//! Python code can import. Inspired by Gleam's `prelude.mjs` approach:
//! a static template embedded in the compiler and copied into each package.

/// The content of `asatsuyu_prelude.py`.
///
/// Provides `Ok[T]` and `Error[E]` as frozen dataclasses, plus a PEP 695
/// `Result[T, E]` type alias. Future additions (e.g., `PyException`) will
/// be added here as the FFI layer matures.
pub(crate) const PRELUDE_PY: &str = r"# asatsuyu_prelude.py — Generated by Asatsuyu, do not edit
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Ok[T]:
    value: T


@dataclass(frozen=True, slots=True)
class Error[E]:
    error: E


type Result[T, E] = Ok[T] | Error[E]
";
