//! Pure-Python compatibility shim and maturin mixed-layout templates.
//!
//! Issue 43 introduces the native `PyO3` runtime crate. This module provides:
//! - [`RUNTIME_SHIM_PY`] — pure-Python fallback for `_asatsuyu_runtime`
//! - [`RUNTIME_STUB_PYI`] — type stubs for the native extension (PEP 561)
//! - [`MATURIN_LIB_RS`] — thin Rust wrapper for maturin mixed layout
//! - [`maturin_cargo_toml`] — generates `Cargo.toml` for the wrapper crate

/// The content of `_asatsuyu_runtime.py`.
pub(crate) const RUNTIME_SHIM_PY: &str = r#"# _asatsuyu_runtime.py — Generated by Asatsuyu, do not edit
import importlib as _importlib
import traceback as _tb


class AsatsuyuError(RuntimeError):
    """Compatibility fallback matching the native runtime's custom exception."""
    pass


def ffi_available() -> bool:
    return True


def import_module(module_name: str):
    return _importlib.import_module(module_name)


def call_function(module, func_name: str, *args):
    func = getattr(module, func_name)
    return func(*args)


def call_method(obj, method_name: str, *args):
    method = getattr(obj, method_name)
    return method(*args)


def normalize_exception(exc: Exception) -> dict[str, str]:
    return {
        "kind": _classify(exc),
        "exception_type": type(exc).__name__,
        "message": str(exc),
        "module": type(exc).__module__,
        "traceback_summary": "".join(_tb.format_exception(exc)),
    }


def _classify(exc: Exception) -> str:
    if isinstance(exc, OSError):
        return "IoError"
    if isinstance(exc, ValueError):
        return "ValueError"
    if isinstance(exc, TypeError):
        return "TypeError"
    if isinstance(exc, KeyError):
        return "KeyError"
    if isinstance(exc, AttributeError):
        return "AttributeError"
    if isinstance(exc, ImportError):
        return "ImportError"
    if isinstance(exc, ArithmeticError):
        return "ArithmeticError"
    if isinstance(exc, RuntimeError):
        return "RuntimeError"
    return "Other"
"#;

/// Type stubs for the native `_asatsuyu_runtime` extension (PEP 561).
///
/// Enables IDE support (pyright, mypy) for the compiled `PyO3` module.
pub(crate) const RUNTIME_STUB_PYI: &str = "\
# _asatsuyu_runtime.pyi \u{2014} Generated by Asatsuyu, do not edit
from typing import Any

class AsatsuyuError(RuntimeError): ...

def ffi_available() -> bool: ...
def import_module(module_name: str) -> Any: ...
def call_function(module: Any, func_name: str, *args: Any) -> Any: ...
def call_method(obj: Any, method_name: str, *args: Any) -> Any: ...
def normalize_exception(exc: Exception) -> dict[str, str]: ...
";

/// Thin Rust wrapper for maturin mixed layout.
///
/// The generated package's `src/lib.rs` delegates to `register_module`
/// in the `_asatsuyu_runtime` crate.
pub(crate) const MATURIN_LIB_RS: &str = "\
//! Thin re-export wrapper for maturin mixed layout.
//! Generated by Asatsuyu \u{2014} do not edit.

use pyo3::prelude::*;

#[pymodule(name = \"_asatsuyu_runtime\")]
fn init(py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    _asatsuyu_runtime::register_module(py, m)
}
";

/// Generate a `Cargo.toml` for the maturin wrapper crate.
///
/// The dependency path placeholder `PATH_TO_RUNTIME` must be replaced
/// by the user or build tooling with the actual path to the
/// `asatsuyu-runtime-python` crate.
pub(crate) fn maturin_cargo_toml(pkg_name: &str) -> String {
    format!(
        "\
[package]
name = \"{pkg_name}\"
version = \"0.1.0\"
edition = \"2024\"

[lib]
name = \"_asatsuyu_runtime\"
crate-type = [\"cdylib\"]

[dependencies]
pyo3 = {{ version = \"0.28\", features = [\"extension-module\"] }}
_asatsuyu_runtime = {{ path = \"PATH_TO_RUNTIME\" }}
"
    )
}
