//! Pure-Python compatibility shim for `_asatsuyu_runtime`.
//!
//! Issue 43 introduces the native PyO3 runtime crate, but package emission
//! still needs an importable module inside generated Python packages before the
//! later mixed-layout packaging work lands. This shim mirrors the native API so
//! Checked FFI code can consistently import `from <pkg> import _asatsuyu_runtime`.

/// The content of `_asatsuyu_runtime.py`.
pub(crate) const RUNTIME_SHIM_PY: &str = r#"# _asatsuyu_runtime.py — Generated by Asatsuyu, do not edit
import importlib as _importlib
import traceback as _tb


class AsatsuyuError(RuntimeError):
    """Compatibility fallback matching the native runtime's custom exception."""
    pass


def ffi_available() -> bool:
    return True


def import_module(module_name: str):
    return _importlib.import_module(module_name)


def call_function(module, func_name: str, *args):
    func = getattr(module, func_name)
    return func(*args)


def call_method(obj, method_name: str, *args):
    method = getattr(obj, method_name)
    return method(*args)


def normalize_exception(exc: Exception) -> dict[str, str]:
    return {
        "kind": _classify(exc),
        "exception_type": type(exc).__name__,
        "message": str(exc),
        "module": type(exc).__module__,
        "traceback_summary": "".join(_tb.format_exception(exc)),
    }


def _classify(exc: Exception) -> str:
    if isinstance(exc, OSError):
        return "IoError"
    if isinstance(exc, ValueError):
        return "ValueError"
    if isinstance(exc, TypeError):
        return "TypeError"
    if isinstance(exc, KeyError):
        return "KeyError"
    if isinstance(exc, AttributeError):
        return "AttributeError"
    if isinstance(exc, ImportError):
        return "ImportError"
    if isinstance(exc, ArithmeticError):
        return "ArithmeticError"
    if isinstance(exc, RuntimeError):
        return "RuntimeError"
    return "Other"
"#;
