[package]
name = "asatsuyu-ast"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "CST to untyped AST conversion for the Asatsuyu language"

[lints]
workspace = true

[dependencies]
asatsuyu-syntax = { workspace = true }
asatsuyu-parser = { workspace = true }
