[package]
name = "asatsuyu-lexer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Lexer for the Asatsuyu language"

[lints]
workspace = true

[dependencies]
asatsuyu-syntax = { workspace = true }
logos = { workspace = true }
smol_str = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
