[package]
name = "asatsuyu-hir"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "High-level IR with name resolution and desugaring for the Asatsuyu language"

[lints]
workspace = true

[dependencies]
asatsuyu-syntax = { workspace = true }
asatsuyu-ast = { workspace = true }
la-arena = { workspace = true }
smol_str = { workspace = true }

[dev-dependencies]
asatsuyu-parser = { workspace = true }
